### ISSUE TITLE
Chapter 9 commentary

### ISSUE THREAD

**Issue by bryceweiner** [bitcoinbook/bitcoinbook#100]
Thank you for the opportunity to provide feedback on your work!  

I might add a little more information regarding the algorithms used and how they impact the networks. ASICs play a large factor in the long term viability of a coin as it drastically increases the efficiency and decreases power consumption. There's a point at which the adoption of an algorithm reaches a critical mass and the ability to develop and mass produce ASICs becomes profitable.  While Bitcoin was all that was necessary for SHA-256, hashrates for coins shown on liteshack.com shows that the ecosystem of Scrypt coins in circulation represents a siginficant portion of the financial drive for Scrypt ASICs not just Litecoin.

At this point it should be said that the speculation on altcoins, even Litecoin, is that they will fulfill their stated use case and many coins launched this year have already had all of their available wealth extracted and have already died (the blockchains have stopped moving).  

If blockchain technology isn't already in use "behind the scenes" in many applications it may very well be in the next few months.  The ability for a decentralized ledger with triple entry accounting has value outside of simple currencies.  When it comes to non-currency applications, the Cambrian explosion in the altmarket has created several valuable new technologies, such as the various methods for difficulty regulation, and maintained several older technologies that are not really popular with Bitcoin, such as merged mining. These sorts of "experiments" are invaluable when leveraged against the development of things such as non-monetized blockchains for elections or access control.

**Comment by mikong** [comment]
Hi @bryceweiner. Your commentary is informative, but can you clarify how this is an issue with the chapter? Are you suggesting to discuss ASICs in more detail?

Based on what I've read so far in this draft book (tbh, I've still read a small part of the book, but I'm catching up), I think it is the intention of the author to stay away from speculation, value, profitability, likelihood of adoption (and so on) of these altcoins. It seems to focus more on the technical characteristics and possible applications, and not on the popularity of these altcoins (though undeniably a factor in the selection of what's included). It seems you're suggesting to discuss how algorithms can affect incentives in the market, and the viability of these digital currencies, and imho, it doesn't seem to be part of the book's scope. I'm just sharing my impressions, and trying to understand this issue. I'm probably missing something, and I apologize if I totally misunderstood your post.

The use of blockchain technology in applications other than currency is already discussed in the chapter. Unless, you actually emphasize the "behind the scenes" aspect of it. In that sense, we can't confirm their existence because they are "behind the scenes". Nevertheless, with the amount of research going into the technology, I would be surprised if it's not used in ways we haven't heard of.

**Comment by enderminh** [comment]
Bug triage.

Closing this bug out as it's not a concrete suggestion. We don't want to get into speculations of all altcoins, and the use of blockchain technology for non-currencies is already discussed a little bit in this chapter.
