### ISSUE TITLE
Figure 6-6 question

### ISSUE THREAD

**Issue by belovachap** [bitcoinbook/bitcoinbook#118]
In https://github.com/aantonop/bitcoinbook/blob/develop/images/InventorySynchronization.png when Node B sends the `getblocks` request to Node A does Node A ever send back some sort of acknowledgement to Node B? Or is a lack of a response to a `getblocks` request normal?

I'm also a little confused on the timing of those initial messages. It looks like Node A actually sends a `getblocks` request right before it hears the first `getblocks` from Node B. Does this illustrate a point in the text that I maybe missed?

**Comment by enderminh** [comment]
I am going to take a stab at answering this, and Andreas (or anyone else) can correct me if I wrong.

The `getblocks` call contains a list of block hashes that the originating client knows about. It starts out with the tip of its branch(es), and the geometrically gets sparser towards to the genesis block. Let's say you only have one branch, and the tip of your chain is block 300,000. As an example, the `getblocks` might include the hash for block 300,000 and 299,998 and 299,990 and 299,950 and 299,000 and 270,000 and 200,000.

The node receiving the `getblocks` call will then find from this list of block hashes the most recent common ancestor it can find in its block chain (with possibly even going as far as the genesis block).  Once the most recent common ancestor is found, it will send all the hashes of subsequent blocks in the `inv` message back to the caller.

In this example, I think that Node A will also return an `inv` response back to Node B. However, the actual content of this `inv` depends on what Node B's "geometric search" block hash values are. If Node B's list of hashes in its geometric search actually includes the tip of Node A's chain, then Node A returns an empty `inv`. If the search contains a block hash a little older in Node A's chain, node A will return the hashes of some of its last blocks in the blockchain (which Node B will simply ignore, since it can locate them all already). 

So, the order in which `getblocks` are called is irrelevant. 

Does this answer your question?

Disclaimer: I haven't developed any bitcoin code, but this is my understanding based on protocol references online.

**Comment by enderminh** [comment]
Bug triage.

Not a real bug/suggestion, but just a question, so I am closing this.
