### ISSUE TITLE
Chapter 4: Suggestion to explain how vanity pools don't have your private key (split-key)

### ISSUE THREAD

**Issue by Siecje** [bitcoinbook/bitcoinbook#136]

**Comment by enderminh** [comment]
Re-assigning to Andreas.

Is it worth explaining split-key vanity pools in such an early chapter?

**Comment by rakete1** [comment]
While reading the vanity pool chapter I asked myself how this could be safe if the "miner" knows the private key. Investigating deeper I realized that this is not a security issue because of the split-key algorithm applied.
Maybe a single sentence with a reference to a complete explanation would help the reader to understand that this process is safe.
