### ISSUE TITLE
(Chapter 4) The order of the elliptic curve is not less than 2^256

### ISSUE THREAD

**Issue by fpelliccioni** [bitcoinbook/bitcoinbook#189]
According to my calculations and Wolfram Alpha, n = 1.158 \* 10^77, the order of the elliptic curve, is not less than 2^256.

See: 
    https://www.wolframalpha.com/input/?i=1.158+*+10%5E77+%3E+2%5E256

On Chapter 4, section: "Generating a private key from a random number". Text:

> More accurately, the private key can be any number between +1+ and +n - 1+, where n is a constant (n = 1.158 \* 10^77^, **slightly less than** 2^256^) defined as the order of the elliptic curve used in bitcoin (see <<elliptic_curve>>). To create such a key, we randomly pick a 256-bit number and **check that it is less than +n - 1+**.

Thanks and regards,
Fernando Pelliccioni

**Comment by wbnns** [comment]
@fpelliccioni Hello, please submit this for review via the book's [errata page](http://www.oreilly.com/catalog/errata.csp?isbn=0636920032281) on O'Reilly.com.

**Comment by fpelliccioni** [comment]
Submitted

http://www.oreilly.com/catalog/errataunconfirmed.csp?isbn=0636920032281

**Comment by nothingmuch** [comment]
The order of the curve has to be less than 2^256, otherwise the key could
not be encoded as a 256 bit string.

According to http://www.secg.org/SEC2-Ver-1.0.pdf (secp256r1 spec), n
= 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
= 115792089237316195423570985008687907852837564279074904382605163141518161494337,
which rounds to 1.158e77.

The parenthetical statement can be improved for clarity, but IMHO it's
correct

**Comment by wbnns** [comment]
@nothingmuch Thank you for the additional thoughts and feedback!
