### ISSUE TITLE
Differentiate between "Bitcoin" (protocol, network) and "bitcoin" (unit of currency)

### ISSUE THREAD

**Issue by DePasqualeOrg** [bitcoinbook/bitcoinbook#427]
In this book, the word "bitcoin" is generally written in lowercase. This differs from the usage specified on [bitcoin.org](https://bitcoin.org/en/vocabulary#bitcoin) and the [Bitcoin Wiki](https://en.bitcoin.it/wiki/Help:Introduction#Capitalization_.2F_Nomenclature), both of which recommend capitalizing the word when referring to the protocol or network and writing it lowercase in reference to the unit of currency. Vice's Motherboard blog also has a [post](https://motherboard.vice.com/en_us/article/qvve7q/why-motherboard-is-capitalizing-bitcoin-again) explaining that this usage aids readability.

Is there a rationale for always writing "bitcoin" lowercase? If computer languages (Python, JavaScript) and protocols (Ethernet, File Transfer Protocol) are generally capitalized, why not write "Bitcoin" when referring to the protocol?

**Comment by mihael** [comment]
https://github.com/bitcoinbook/bitcoinbook/pull/407

Hi. Is there a protocol named Bitcoin? Isn't the currency Bitcoin? Cheers

**Comment by DePasqualeOrg** [comment]
See the Bitcoin Wiki link above:

> Since Bitcoin is both a currency and a protocol, capitalization can be confusing. Accepted practice is to use Bitcoin (singular with an upper case letter B) to label the protocol, software, and community, and bitcoins (with a lower case b) to label units of the currency.

**Comment by mihael** [comment]
Well, industry writes "Euro", but it is in fact "euro". I do not see any problem with the current naming in this book. It is clear from the Wiki: `Bitcoin is both a currency and a protocol`.

It is not so clear where the "Accepted practice" assumption comes from though!

If I check an example exchange, let's check bitstamp.net:
![screen shot 2017-12-25 at 10 47 27](https://user-images.githubusercontent.com/7082/34337619-43754ef6-e961-11e7-8be5-f1ae5d633ce5.jpg)

And then check coinbase.com:
<img width="1101" alt="screen shot 2017-12-25 at 10 52 58" src="https://user-images.githubusercontent.com/7082/34337707-fa4e6018-e961-11e7-8525-3d5ae430ebfe.png">

**Comment by DePasqualeOrg** [comment]
What industry writes "Euro"? "euro" (lowercase) is very clearly the correct spelling. Just because people disregard or are unaware of the rules doesn't mean that they don't exist.

Bitstamp's website (and those of many other exchanges) has not been carefully copy edited, by the way. You can find all kinds of irregularities and mistakes on there.

**Comment by mihael** [comment]
Industry(google) writes Euro:
<img width="813" alt="screen shot 2017-12-25 at 10 59 22" src="https://user-images.githubusercontent.com/7082/34337797-c83d845e-e962-11e7-97c3-7836aafca36a.png">

And it also uses capital letter on the Bitcoin:
<img width="793" alt="screen shot 2017-12-25 at 10 59 41" src="https://user-images.githubusercontent.com/7082/34337813-e6c7cd44-e962-11e7-9f05-9331dff43202.png">

**Comment by mihael** [comment]
When this is said `Bitstamp's website (and those of many other exchanges) has not been carefully copy edited,`, how can this be prooved, how can one know what a mistake is and what not without working in that particular company as copy editor...

And when rules are mentioned, where are the mentioned rules, where can I read the rules mentioned?

Cheers

**Comment by DePasqualeOrg** [comment]
Again, just because you can find examples of companies that ignore the established rules for English, that doesn't mean that their usage is correct.

As for who determines correct usage, there is no central authority for the English language, but a good guideline would be to check various popular style guides, such as Garner's Modern English Usage, the Chicago Manual of Style, or style guides used by periodicals and publishing houses. In the case of currencies such as "dollar" and "euro", the correct usage is clear from these style guides: currencies are written in lowercase.

As for the mistakes and irregularities I mentioned, just check the [Bitstamp FAQ](https://www.bitstamp.net/faq/), for instance. There they write "bitcoin" lowercase, unlike on the front page. They also use non-standard quotation marks for English (» «), among other grammatical mistakes. Companies in this space simply don't invest in professional copy editing, so their usage should be viewed skeptically.

**Comment by mihael** [comment]
I agree on the english rules @a-dpq, and good point on [Bitstamp FAQ](https://www.bitstamp.net/faq/)  showing signs of "lame" copy editing.

Bitstamp's FAQ section does indeed look like "copy" mistakes:
<img width="528" alt="screen shot 2017-12-25 at 11 20 19" src="https://user-images.githubusercontent.com/7082/34338153-10ee027a-e966-11e7-88cd-bdb50c8c4d71.png">

So my next step would be to write a letter to some of these exchanges and ask them if they are willing to modify their copy and follow the english language rules about writing currency names.

Is there a PR for this issue @a-dpq? 

Cheers

**Comment by DePasqualeOrg** [comment]
It looks like this issue was mentioned in a previous [pull request](https://github.com/bitcoinbook/bitcoinbook/pull/407), but no resolution was reached.

I also submitted a pull request with some corrections to the first few chapters of the book a few weeks ago, but there has been no reaction to it since then. Is anyone actively maintaining this project?

**Comment by mihael** [comment]
I just read this [post](https://motherboard.vice.com/en_us/article/qvve7q/why-motherboard-is-capitalizing-bitcoin-again).

Article does expose the real problem with these renaming schemes:

```
Should the new version of Bitcoin, called Bitcoin Cash, be capitalized when Bitcoin proper is not? What kind of message does that send to our readers? Does one version "deserve" to be capitalized while the other does not? On the other hand, which implementation "deserves" to be treated with the kind of familiarity that the internet does, and why?
```

*TBH IMHO I think the article is worried about how to rename Bitcoin Cash into Bitcoin and get away with it.*

Article sums up with a vaguely expressed solution to the described problem, this is how the article ends:
```
We need to keep our articles readable. We also need to avoid the illusion of preference. Above all, we need to be careful about which technologies we normalize. For all these reasons, we're going to capitalize all cryptocurrencies-as-systems and de-capitalize their denominations. Litecoin, Dogecoin, Bitcoin, Bitcoin Cash, Ethereum, etc.
```

The last two sentences are not clear to me and are even more confusing than this issue it self!

`It looks like this issue was mentioned in a previous pull request, but no resolution was reached.` - Sorry, but is this pretending or just not seeing? I was the one referencing this issue with that PR (today! after reading this issue), since it looked like the same attempt to bring this "renaming" into the book.

To me it looks like this project is still maintained, last master commit was end of August:

Latest commit 6354bb9  on Aug 24 @wbnns  wbnns readme: Update instruction; PRs to develop branch

**Comment by DePasqualeOrg** [comment]
I think the approach outlined in the Motherboard post is clear, and it agrees with the links I posted above: capitalize "Bitcoin", "Bitcoin Cash", etc. when referring to the protocol, and use lowercase when referring to the currency.

**Comment by mihael** [comment]
When someone writes in the public: "new version of Bitcoin, called Bitcoin Cash", I feel like the article is not about anything useful, just working for a pro-fork-agenda and part of FUD.

One can not create a new version of Bitcoin or bitcoin, there is exactly 21m bitcoins/Bitcoins. It is not possible, since Bitcoin and/or bitcoin, whatever You want to name the original bitcoin, are still very much the same protocol and chain as before (this can be verified at any time). While the Cash's chain has split out, branched off and runs on different consensus, so it can not be the original in any way imaginable.

Renaming back to bitcoin when talking currency, and using Bitcoin for the protocol, would allow article writers like the one linked, to make claims:

`I bought some bitcoin via Bitcoin Cash protocol`???

Which would imply, bitcoin = Bitcoin Cash! But it is not.

So to me, these renaming changes look like an attempt to hide the fact Bitcoin Cash is not Bitcoin. Since article writers could write about "bitcoin" but have "Bitcoin Cash" in mind.

Anyway, glad I was able to figure out what's going on here behind the scene. 

A big 👎 from me on this issue.

LOL

**Comment by DePasqualeOrg** [comment]
I think you may be misreading the article. As I understand it, Motherboard will capitalize "Bitcoin" and "Bitcoin Cash" (as protocols) and write "bitcoin" and "bitcoin cash" when referring to units of currency. I don't think they want to call "bitcoin cash" "bitcoin".

Let's keep this discussion about usage in the book. It would also be good to have input from other contributors.

**Comment by KanoczTomas** [comment]
Hello,  I agree with @a-dpq ...it is purely naming convention thing. The protocol itself is Bitcoin. The unit of account, bitcoin, does not even exist in the protocol. As we know all transactions have values in satoshis on wire and such a thing as bitcoin, mili bitcoin, etc. are all just convenient ways to refer to satoshi units. The reference for any usage is bitcoin.org and the bitcoin wiki. And they state it crearly. 

It is asimilar problem to Sun and sun ... or in many languages Earth and earth (well in English the lowercase does not mean soil, but in many languages it does and capitalisation is the only way to distinguish. Of course one can know which one is used from context). If we refer to the star closest to us it should be Sun. If we refer to a star which has orbiting planets, it is a sun.

The book being a very good reference should address these correctly!

**Comment by mihael** [comment]
Took a look at the referenced PRs. And can only confirm my assumption, that this issue together with the PR is not doing anything useful, and even introduces more confusion.

Which one of the bellow would be correct @a-dpq  ?

`ECDSA is a cryptographic algorithm used by Bitcoin`
`ECDSA is a cryptographic algorithm used by bitcoin`

See here (just exanmple, there's more of such discrepancies in Your PR) https://github.com/bitcoinbook/bitcoinbook/pull/429/files#diff-c72e60ff726281fd4f9d2de7897a727bR61

If You want to adjust the book to be inline with the silly article mentioned above, then You should choose not to edit the above as You did in Your PR, since that part of the book is describing a protocol. LOL

**Comment by DePasqualeOrg** [comment]
@mihael, please look at the notes for my pull request. Except for the glossary, the entire rest of the book writes "bitcoin" in lowercase. I changed "Bitcoin" to "bitcoin" in the glossary to agree with the usage in the rest of the book. Please note that this actually contradicts the usage recommended in the above links. I have not applied these rules to the book – this is why I've opened an issue to discuss this point. Whatever is decided, the convention should be applied consistently throughout the book. I think that's an important point and worth discussing.

**Comment by aantonop** [comment]
Will change glossary to lower-case. I'm not using the "convention" of differentiating based on capitalization, because I think that context is better than capitalization, and ambiguity is somewhat unavoidable

**Comment by DePasqualeOrg** [comment]
https://github.com/bitcoinbook/bitcoinbook/commit/a3229bbbc0c929dc53ec11365051a6782695cb52
