### ISSUE TITLE
Chapter 7 P2SH example (page 153 in print): Confusing presentation of redeem script may lead to incorrect script hash. 

### ISSUE THREAD

**Issue by grisha** [bitcoinbook/bitcoinbook#438]
At the top of page 153, the way the Mohammed's company redeem script is represented, it is easy to arrive at a different hash,
`c431fa3ff3985f09cf1250ff63a4a1232bb20af7`, not `54c557e07dde5bb6cb791c7a540e0a4796f5e97e`.

Using `bx`, if the script is in a file named `script` with the following content:
```txt
2 [04C16B8698A9ABF84250A7C3EA7EEDEF9897D1C8C6ADF47F06CF73370D74DCCA01CDCA79DCC5C395D7EEC6984D83F1F50C900A24DD47F569FD4193AF5DE762C58704A2192968D8655D6A935BEAF2CA23E3FB87A3495E7AF308EDF08DAC3C1FCBFC2C75B4B0F4D0B1B70CD2423657738C0C2B1D5CE65C97D78D0E34224858008E8B49047E63248B75DB7379BE9CDA8CE5751D16485F431E46117B9D0C1837C9D5737812F393DA7D4420D7E1A9162F0279CFC10F1E8E8F3020DECDBC3C0DD389D99779650421D65CBD7149B255382ED7F78E946580657EE6FDA162A187543A9D85BAAA93A4AB3A8F044DADA618D087227440645ABE8A35DA8C5B73997AD343BE5C2AFD94A5043752580AFA1ECED3C68D446BCAB69AC0BA7DF50D56231BE0AABF1FDEEC78A6A45E394BA29A1EDF518C022DD618DA774D207D137AAB59E0B000EB7ED238F4D800] 5 CHECKMULTISIG
```
Then 
```sh
$ bx script-encode < script | bx sha256 | bx ripemd160 
c431fa3ff3985f09cf1250ff63a4a1232bb20af7
```

The trick is that each pubkey needs to be separately pushed onto the stack, so to get the right hash we need (this time not using a file, just echo, for clarity):

```sh
echo \
2 \
[04C16B8698A9ABF84250A7C3EA7EEDEF9897D1C8C6ADF47F06CF73370D74DCCA01CDCA79DCC5C395D7EEC6984D83F1F50C900A24DD47F569FD4193AF5DE762C587] \
[04A2192968D8655D6A935BEAF2CA23E3FB87A3495E7AF308EDF08DAC3C1FCBFC2C75B4B0F4D0B1B70CD2423657738C0C2B1D5CE65C97D78D0E34224858008E8B49] \
[047E63248B75DB7379BE9CDA8CE5751D16485F431E46117B9D0C1837C9D5737812F393DA7D4420D7E1A9162F0279CFC10F1E8E8F3020DECDBC3C0DD389D9977965] \
[0421D65CBD7149B255382ED7F78E946580657EE6FDA162A187543A9D85BAAA93A4AB3A8F044DADA618D087227440645ABE8A35DA8C5B73997AD343BE5C2AFD94A5] \
[043752580AFA1ECED3C68D446BCAB69AC0BA7DF50D56231BE0AABF1FDEEC78A6A45E394BA29A1EDF518C022DD618DA774D207D137AAB59E0B000EB7ED238F4D800] \
5 CHECKMULTISIG \
| bx script-encode | bx sha256 | bx ripemd160
54c557e07dde5bb6cb791c7a540e0a4796f5e97e
```
I think it would have been clearer if the script either had the pubkeys separated by a space, similarly to how the `2`, the `5` and `CHECKMULTISIG` are, or (even better) included the above `bx` example.

I'd be happy to make a PR, but I need guidance on whether to go with spaces or the brackets (and bx example?).

**Comment by aantonop** [comment]
Fixed for third print bitcoinbook/bitcoinbook@32464c86dd578388a4d949d46b48ba2948a7d62d. I decided to use your bx example, thanks!

**Comment by miketery** [comment]
For this line: https://github.com/bitcoinbook/bitcoinbook/commit/32464c86dd578388a4d949d46b48ba2948a7d62d#diff-43b9eedf46013fba3894992f19dc010a80aee016d8f4e9e5e6aec4af91695a35R128

I believe each key needs to be prepended with 0x41 (number of bytes to push onto stack: 65 bytes per address), otherwise I'm not able to generate the same hash160. So it should really be:

4104C16B8698A9ABF84250A7C3EA7EEDEF9897D1C8C6ADF47F06CF73370D74DCCA01CDCA79DCC5C395D7EEC6984D83F1F50C900A24DD47F569FD4193AF5DE762C5874104A2192968D8655D6A935BEAF2CA23E3FB87A3495E7AF308EDF08DAC3C1FCBFC2C75B4B0F4D0B1B70CD2423657738C0C2B1D5CE65C97D78D0E34224858008E8B4941047E63248B75DB7379BE9CDA8CE5751D16485F431E46117B9D0C1837C9D5737812F393DA7D4420D7E1A9162F0279CFC10F1E8E8F3020DECDBC3C0DD389D9977965410421D65CBD7149B255382ED7F78E946580657EE6FDA162A187543A9D85BAAA93A4AB3A8F044DADA618D087227440645ABE8A35DA8C5B73997AD343BE5C2AFD94A541043752580AFA1ECED3C68D446BCAB69AC0BA7DF50D56231BE0AABF1FDEEC78A6A45E394BA29A1EDF518C022DD618DA774D207D137AAB59E0B000EB7ED238F4D800
