### ISSUE TITLE
Ch. 12: Incorrect fees in Lightning Network example

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#461]
Carol's final balance of "3.002" and Bob's of "3.003" should both be "3.001": Alice pays 0.001 bitcoin to each participant in the payment channel.

**Comment by 30mb1** [comment]
@rrthomas Here we are talking about channel's balances, so its ok.
[Alice <-> Bob] channel balance is [ 0.997 BTC - 3.003 BTC ] and
[Bob <-> Carol] channel balance is [ 0.998 BTC - 3.002 BTC ].
Bob received 1.003 on first channel and sended 1.002 on second channel, so that he got his 0.001 profit. Same for the rest of participants in chain.

**Comment by rrthomas** [comment]
Thanks for the explanation.

**Comment by pavlovdog** [comment]
@30mb1 thanks!
