### ISSUE TITLE
Chapter 2: minor issues

### ISSUE THREAD

**Issue by trulex** [bitcoinbook/bitcoinbook#535]
>  Soon, Jing and other miners upgraded to more specialized hardware, such as high-end dedicated graphical processing units (GPUs) cards such as those used in gaming desktops or consoles.

If you don't read the part with parentheses, it says "graphical processing units cards", which doesn't sound correct. Also, "such as" is used twice.

> Let’s assume that Bob pays his web designer Gopesh in Bangalore for a new website page.

It's enough to say only "website".

**Comment by AbdussamadA** [comment]
There is another problem with this chapter under creating outputs:

> "This output is payable to whoever can present a signature from the key corresponding to Bob’s public address." 

The use of "public address" instead of just address leads to all sorts of confusion. People start talking about private addresses instead of private keys. They confuse public keys and extended public keys with their address. Please change this to just address.

**Comment by wbnns** [comment]
@trulex @AbdussamadA Thank you.

+ 59cd645
+ 70d1d80
+ 7488970
